version: '2'
services:
  libreoffice:
#    image: ''
    build: .
    container_name: 'libreoffice'
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
      - '/Users/albertojorgealvarezbruned/Documents/ubuntu_netbeans/home:/home/libreofficeuser/home'
    environment:
      - DISPLAY=$DISPLAY_MAC
